force-app/main/default/objects/Historico_de_Calculo__c/Historico_de_Calculo__c.object-meta.xml
<CustomObject>
    <label>Histórico de Cálculo</label>
    <nameField>
        <label>Histórico de Calculo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Cálculo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_de_Calculo__c/fields/Calculo_Realizado__c.field-meta.xml
<CustomField>
    <fullName>Calculo_Realizado__c</fullName>
    <label>Cálculo Realizado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_de_Calculo__c/fields/Resultado_do_Calculo__c.field-meta.xml
<CustomField>
    <fullName>Resultado_do_Calculo__c</fullName>
    <label>Resultado do Cálculo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Veiculo__c/Veiculo__c.object-meta.xml
<CustomObject>
    <label>Veiculo</label>
    <nameField>
        <label>Chassi</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Veiculos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CalculadoraController.cls
public class CalculadoraController {
    
    @AuraEnabled
    public static void registraCalculo(String calculoRealizado, String resultado){
        
        Historico_de_Calculo__c hc = new Historico_de_Calculo__c();
        hc.Calculo_Realizado__c = calculoRealizado;
        hc.Resultado_do_Calculo__c = resultado;
        
        insert hc; 
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getCars(){
        List<Veiculo__c> cars = [SELECT Name FROM Veiculo__c];
        List<String> carNames = new List<String>();
        for(Veiculo__c car : cars){
            carNames.add(car.Name);
        }

        return carNames;
    }

    @AuraEnabled
    public static void insertAccount(String name){
        
        Account acc = new Account();
        acc.Name = name;
        insert acc;
    }
}